function VirginiaWebsite
    clc
    
    %% imports tidbits
    fileloc='C:\Users\ltsai\Documents\Personal\Github\VirginiaWebsite\VirginiaWebsite\';
%     'images\fulls\'
    [ImageName,Subtitle,Tag1,Tag2,Tag3,Tag4,A,B,C,D] = importfile([fileloc,'script\PhotoIndex.xlsx']);

    header=fileread([fileloc,'script\Header.txt']);
    footer=fileread([fileloc,'script\Footer.txt']);    
    snippet=fileread([fileloc,'script\Image.txt']);    
    %converts display & feature to binary
    Tags=join([Tag1,Tag2,Tag3,Tag4]);
      
    index=[fileloc,'index.html'];
    
    source_files = dir(fullfile([fileloc,'images/fulls/'], '*.jpg'));
    count=length(source_files);
    lengths=[0 0 0];
    col1='<div>';
    col2='<div>';
    col3='<div>';
    
    for i=1:length(source_files)
        a=length(source_files)+1-i;
        img=imread([fileloc,'images/thumbs/',char(ImageName(a+1))]);
        ims=size(img);
        relh=ims(1)/ims(2);
        [M,ind] = min(lengths);
        
        temptext=snippet;
        temptext=strrep(temptext,'[tags]',Tags(a+1));
        temptext=strrep(temptext,'[path]',ImageName(a+1));
        temptext=strrep(temptext,'[description]',Subtitle(a+1));
        
        lengths(ind)=lengths(ind)+relh+.2;
        switch ind
            case 1
                col1=[col1 temptext];
            case 2
                col2=[col2 temptext];
            case 3
                col3=[col3 temptext];
        end
        
    end
    col1=[col1,'</div>'];
    col2=[col2,'</div>'];
    col3=[col3,'</div>'];
    
    %% create 1 file
    fid = fopen(index,'w');
    fprintf(fid, '%s', header);
    fclose(fid);
    
    fid = fopen(index,'a');
    fprintf(fid, '%s', col1);
    fprintf(fid, '%s', col2);
    fprintf(fid, '%s', col3);
        
    fprintf(fid, '%s', footer);
    fclose(fid);
   
end

function [ImageName,Subtitle,Tag1,Tag2,Tag3,Tag4,A,B,C,D] = importfile(workbookFile,sheetName,startRow,endRow)
%IMPORTFILE Import data from a spreadsheet
%   [ImageName,Subtitle,Tag1,Tag2,Tag3,Tag4,A,B,C,D] = IMPORTFILE(FILE)
%   reads data from the first worksheet in the Microsoft Excel spreadsheet
%   file named FILE and returns the data as column vectors.
%
%   [ImageName,Subtitle,Tag1,Tag2,Tag3,Tag4,A,B,C,D] =
%   IMPORTFILE(FILE,SHEET) reads from the specified worksheet.
%
%   [ImageName,Subtitle,Tag1,Tag2,Tag3,Tag4,A,B,C,D] =
%   IMPORTFILE(FILE,SHEET,STARTROW,ENDROW) reads from the specified
%   worksheet for the specified row interval(s). Specify STARTROW and
%   ENDROW as a pair of scalars or vectors of matching size for
%   dis-contiguous row intervals. To read to the end of the file specify an
%   ENDROW of inf.%
% Example:
%   [ImageName,Subtitle,Tag1,Tag2,Tag3,Tag4,A,B,C,D] = importfile('PhotoIndex.xlsx','Sheet1',1,1000);
%
%   See also XLSREAD.

% Auto-generated by MATLAB on 2020/12/21 20:59:54

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 3
    startRow = 1;
    endRow = 1000;
end

%% Import the data
[~, ~, raw] = xlsread(workbookFile, sheetName, sprintf('A%d:J%d',startRow(1),endRow(1)));
for block=2:length(startRow)
    [~, ~, tmpRawBlock] = xlsread(workbookFile, sheetName, sprintf('A%d:J%d',startRow(block),endRow(block)));
    raw = [raw;tmpRawBlock]; %#ok<AGROW>
end
stringVectors = string(raw(:,[1,2,3,4,5,6,7,8,9,10]));
stringVectors(ismissing(stringVectors)) = '';

%% Allocate imported array to column variable names
ImageName = stringVectors(:,1);
Subtitle = stringVectors(:,2);
Tag1 = stringVectors(:,3);
Tag2 = stringVectors(:,4);
Tag3 = stringVectors(:,5);
Tag4 = stringVectors(:,6);
A = stringVectors(:,7);
B = stringVectors(:,8);
C = stringVectors(:,9);
D = stringVectors(:,10);

end